---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: eotk-on-k8s
  namespace: eotk-on-k8s

resources:
  - onion-exporter
  - tor-exporter
  - nginx-exporter
  - deployment.yaml
  - hpa.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - service.yaml
  - spc.yaml
