---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eotk-on-k8s
  namespace: eotk-on-k8s
spec:
  provider: vault
  parameters:
    roleName: eotk_on_k8s
    objects: |
      ## onion secrets
      # example.com
      - objectName: hff4c4h4l62ei2mmtkfuuu6oxwr26uycozsdnbngvxytpa6vhnoshoqd.v3pub.key
        secretPath: "secret/eotk-on-k8s/onion-keys/example_com"
        secretKey: "pub"
      - objectName: hff4c4h4l62ei2mmtkfuuu6oxwr26uycozsdnbngvxytpa6vhnoshoqd.v3sec.key
        secretPath: "secret/eotk-on-k8s/onion-keys/example_com"
        secretKey: "sec"
      ## SSL certs (filename is 20 chars plus -v3 prefix)
      # example.com
      - objectName: hff4c4h4l62ei2mmtkfu-v3.cert
        secretPath: "secret/eotk-on-k8s/ssl-certs/example_com"
        secretKey: "cert"
      - objectName: hff4c4h4l62ei2mmtkfu-v3.pem
        secretPath: "secret/eotk-on-k8s/ssl-certs/example_com"
        secretKey: "pem"
